FROM php:8.3-fpm-alpine AS php
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache freetype libpng libjpeg-turbo libzip && \
    docker-php-ext-configure gd --with-freetype --with-jpeg && \
    docker-php-ext-install gd intl pdo_mysql zip mbstring exif pcntl bcmath

WORKDIR /var/www/html
COPY . /var/www/html
RUN composer install --no-dev --optimize-autoloader --no-interaction && \
    php artisan key:generate --no-interaction --force && \
    php artisan config:cache && php artisan route:cache && \
    php artisan view:cache && \
    php artisan migrate --force --no-interaction  # DB limpa + migrations